server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git: #配置文件位置，git上
          uri: https://github.com/tianxiang2017/edct
          search-paths: config-repo
#  rabbitmq:
#    host: rabbitmq.ztxlearn.xyz