server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tianxiang2017/edct
          search-paths: config-repo
          username: tianxiang2017@gmail.com
          password: root123!A
#  rabbitmq:
#    host: rabbitmq.ztxlearn.xyz