server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry.ztxlearn.xyz:8761/eureka/

zuul:
  routes:
    api-a:
      path: /account/**
      serviceId: account
    api-b:
      path: /api-b/**
      serviceId: service-feign