server:
  port: 8761

eureka:
  instance:
    hostname: registry.ztxlearn.xyz
    #prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@${eureka.instance.hostname}:${server.port}/eureka/

